name: Wails build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          [
            { name: Zroker, platform: linux/amd64, os: ubuntu-latest },
            { name: Zroker, platform: windows/amd64, os: windows-latest },
            { name: Zroker, platform: darwin/universal, os: macos-latest },
          ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - uses: dAppServer/wails-build-action@v2.2
        with:
          package: false
          node-version: 20
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
          files: build/bin/*
